-- Kampüs Kütüphane Sistemi: database schema
--
-- Bu dosya Sprint 2'de ekipler tarafından doldurulacaktır.
--
-- Kurallar:
--   - Her ekip kendi tablolarını yazar; tabloların sahibi yorum satırında belirtilir.
--   - Tablo ve sütun adları İngilizce, snake_case; tablo adları çoğul (ör. loans).
--   - Başka ekibin tablosuna referans (FOREIGN KEY) veren tablolar, o ekiple
--     Scrum of Scrums'ta konuşularak tasarlanır ve docs/interface-contract.md'ye yazılır.
--   - Bu dosya app/core/ altında olduğu için değişiklikler Scrum Master'ların onayını gerektirir.
--
-- Örnek biçim:
--
--   -- Owner: team-catalog
--   DROP TABLE IF EXISTS books;
--   CREATE TABLE books (
--       id     INTEGER PRIMARY KEY AUTOINCREMENT,
--       isbn   TEXT    NOT NULL UNIQUE,
--       title  TEXT    NOT NULL
--   );
